{% set name = "conda-press" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-press/releases/download/{{ version }}/conda-press-{{ version }}.tar.gz
  sha256: 40509fd610a7ff119c2883a6b938c23a1c5f44ddb6439be60c42577c7e3f6dcb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
    - requests
    - xonsh
    - lazyasd
    - ruamel.yaml
    - tqdm
    - binutils  # [unix]
    - patchelf  # [linux]

test:
  imports:
    - conda_press
  commands:
    - conda press --help

about:
  home: https://github.com/regro/conda-press
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Press conda packages into wheels'

extra:
  recipe-maintainers:
    - scopatz
    - marcelotrevisani
